required_plugins = %w(vagrant-vbguest)

plugins_to_install = required_plugins.select { |plugin| not Vagrant.has_plugin? plugin }
if not plugins_to_install.empty?
  puts "Installing plugins: #{plugins_to_install.join(' ')}"
  if system "vagrant plugin install #{plugins_to_install.join(' ')}"
    exec "vagrant #{ARGV.join(' ')}"
  else
    abort "Installation of one or more plugins has failed. Aborting."
  end
end

Vagrant.configure("2") do |config|

  config.vm.box = "centos/7"
  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.vm.synced_folder ".", "/shared", type: "virtualbox"
  config.vm.network "forwarded_port", guest: 80, host: 8080, host_ip: "127.0.0.1"
  
  config.vm.provider "virtualbox" do |vb|
    vb.name = "EStore"
	vb.gui = true
	vb.cpus = 4
    vb.memory = "4096"
	vb.customize ["modifyvm", :id, "--vram", "128"]
	vb.customize ["modifyvm", :id, "--clipboard", "bidirectional"]
	vb.customize ["modifyvm", :id, "--draganddrop", "bidirectional"]
	vb.customize ["modifyvm", :id, "--cpuexecutioncap", "90"] 
  end

  config.vm.provision "shell", path: "scripts/provision.sh", privileged: false
  
end
